pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=ready-to-merge
      - check-success=build
    actions:
      merge:
        method: squash
        commit_message: title+body
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build
    actions:
      merge:
        method: squash
